# Basic
name:               "HDMT Lab"
title:              "High Dimensional Multiple Testing Lab"
description:        "this is a page for high dimensional multiple testing lab at the Seoul National University, South Korea"


# URL
url:                http://hdmtlab.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge
 
# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Research"
    href:           "/research"
  - name:           "Publications"
    href:           "/publication"
  - name:           "People"
    href:           "/people"  
  - name:           "Gallery"
    href:           "/gallery"    


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html

